// Code generated by MockGen. DO NOT EDIT.
// Source: link.go
//
// Generated by this command:
//
//	mockgen -source link.go -destination mock_portforward_link_repo/mock_link.go
//

// Package mock_portforward_link_repo is a generated GoMock package.
package mock_portforward_link_repo

import (
	context "context"
	reflect "reflect"

	portforward_link_entity "github.com/agentre-hub/agentre-server/internal/model/entity/portforward_link_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPortForwardLinkRepo is a mock of PortForwardLinkRepo interface.
type MockPortForwardLinkRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPortForwardLinkRepoMockRecorder
	isgomock struct{}
}

// MockPortForwardLinkRepoMockRecorder is the mock recorder for MockPortForwardLinkRepo.
type MockPortForwardLinkRepoMockRecorder struct {
	mock *MockPortForwardLinkRepo
}

// NewMockPortForwardLinkRepo creates a new mock instance.
func NewMockPortForwardLinkRepo(ctrl *gomock.Controller) *MockPortForwardLinkRepo {
	mock := &MockPortForwardLinkRepo{ctrl: ctrl}
	mock.recorder = &MockPortForwardLinkRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortForwardLinkRepo) EXPECT() *MockPortForwardLinkRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPortForwardLinkRepo) Create(ctx context.Context, link *portforward_link_entity.PortForwardLink) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPortForwardLinkRepoMockRecorder) Create(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPortForwardLinkRepo)(nil).Create), ctx, link)
}

// FindByDeviceMapping mocks base method.
func (m *MockPortForwardLinkRepo) FindByDeviceMapping(ctx context.Context, deviceID, mappingID int64) (*portforward_link_entity.PortForwardLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDeviceMapping", ctx, deviceID, mappingID)
	ret0, _ := ret[0].(*portforward_link_entity.PortForwardLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDeviceMapping indicates an expected call of FindByDeviceMapping.
func (mr *MockPortForwardLinkRepoMockRecorder) FindByDeviceMapping(ctx, deviceID, mappingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDeviceMapping", reflect.TypeOf((*MockPortForwardLinkRepo)(nil).FindByDeviceMapping), ctx, deviceID, mappingID)
}

// FindByPrefix mocks base method.
func (m *MockPortForwardLinkRepo) FindByPrefix(ctx context.Context, prefix string) (*portforward_link_entity.PortForwardLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPrefix", ctx, prefix)
	ret0, _ := ret[0].(*portforward_link_entity.PortForwardLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPrefix indicates an expected call of FindByPrefix.
func (mr *MockPortForwardLinkRepoMockRecorder) FindByPrefix(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPrefix", reflect.TypeOf((*MockPortForwardLinkRepo)(nil).FindByPrefix), ctx, prefix)
}
