// Code generated by MockGen. DO NOT EDIT.
// Source: summary.go
//
// Generated by this command:
//
//	mockgen -source summary.go -destination mock_agent_session_repo/mock_summary.go
//

// Package mock_agent_session_repo is a generated GoMock package.
package mock_agent_session_repo

import (
	context "context"
	reflect "reflect"

	agent_session_entity "github.com/agentre-hub/agentre-server/internal/model/entity/agent_session_entity"
	agent_session_repo "github.com/agentre-hub/agentre-server/internal/repository/agent_session_repo"
	gomock "go.uber.org/mock/gomock"
)

// MockSummaryRepo is a mock of SummaryRepo interface.
type MockSummaryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSummaryRepoMockRecorder
	isgomock struct{}
}

// MockSummaryRepoMockRecorder is the mock recorder for MockSummaryRepo.
type MockSummaryRepoMockRecorder struct {
	mock *MockSummaryRepo
}

// NewMockSummaryRepo creates a new mock instance.
func NewMockSummaryRepo(ctrl *gomock.Controller) *MockSummaryRepo {
	mock := &MockSummaryRepo{ctrl: ctrl}
	mock.recorder = &MockSummaryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSummaryRepo) EXPECT() *MockSummaryRepoMockRecorder {
	return m.recorder
}

// CountSummaries mocks base method.
func (m *MockSummaryRepo) CountSummaries(ctx context.Context, q agent_session_repo.SummaryQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSummaries", ctx, q)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSummaries indicates an expected call of CountSummaries.
func (mr *MockSummaryRepoMockRecorder) CountSummaries(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSummaries", reflect.TypeOf((*MockSummaryRepo)(nil).CountSummaries), ctx, q)
}

// CountSummariesByAgent mocks base method.
func (m *MockSummaryRepo) CountSummariesByAgent(ctx context.Context, q agent_session_repo.SummaryQuery) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSummariesByAgent", ctx, q)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSummariesByAgent indicates an expected call of CountSummariesByAgent.
func (mr *MockSummaryRepoMockRecorder) CountSummariesByAgent(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSummariesByAgent", reflect.TypeOf((*MockSummaryRepo)(nil).CountSummariesByAgent), ctx, q)
}

// CountSummariesByPeer mocks base method.
func (m *MockSummaryRepo) CountSummariesByPeer(ctx context.Context, q agent_session_repo.SummaryQuery) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSummariesByPeer", ctx, q)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSummariesByPeer indicates an expected call of CountSummariesByPeer.
func (mr *MockSummaryRepoMockRecorder) CountSummariesByPeer(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSummariesByPeer", reflect.TypeOf((*MockSummaryRepo)(nil).CountSummariesByPeer), ctx, q)
}

// CountSummariesByProjectKey mocks base method.
func (m *MockSummaryRepo) CountSummariesByProjectKey(ctx context.Context, q agent_session_repo.SummaryQuery) ([]agent_session_repo.SummaryProjectKeyCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSummariesByProjectKey", ctx, q)
	ret0, _ := ret[0].([]agent_session_repo.SummaryProjectKeyCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSummariesByProjectKey indicates an expected call of CountSummariesByProjectKey.
func (mr *MockSummaryRepoMockRecorder) CountSummariesByProjectKey(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSummariesByProjectKey", reflect.TypeOf((*MockSummaryRepo)(nil).CountSummariesByProjectKey), ctx, q)
}

// DeleteSummary mocks base method.
func (m *MockSummaryRepo) DeleteSummary(ctx context.Context, userID int64, conversationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSummary", ctx, userID, conversationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSummary indicates an expected call of DeleteSummary.
func (mr *MockSummaryRepoMockRecorder) DeleteSummary(ctx, userID, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSummary", reflect.TypeOf((*MockSummaryRepo)(nil).DeleteSummary), ctx, userID, conversationID)
}

// ListSummariesByUser mocks base method.
func (m *MockSummaryRepo) ListSummariesByUser(ctx context.Context, userID int64) ([]*agent_session_entity.SessionSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSummariesByUser", ctx, userID)
	ret0, _ := ret[0].([]*agent_session_entity.SessionSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSummariesByUser indicates an expected call of ListSummariesByUser.
func (mr *MockSummaryRepoMockRecorder) ListSummariesByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSummariesByUser", reflect.TypeOf((*MockSummaryRepo)(nil).ListSummariesByUser), ctx, userID)
}

// ListSummariesPage mocks base method.
func (m *MockSummaryRepo) ListSummariesPage(ctx context.Context, q agent_session_repo.SummaryPageQuery) ([]*agent_session_entity.SessionSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSummariesPage", ctx, q)
	ret0, _ := ret[0].([]*agent_session_entity.SessionSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSummariesPage indicates an expected call of ListSummariesPage.
func (mr *MockSummaryRepoMockRecorder) ListSummariesPage(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSummariesPage", reflect.TypeOf((*MockSummaryRepo)(nil).ListSummariesPage), ctx, q)
}

// MarkSummaryRead mocks base method.
func (m *MockSummaryRepo) MarkSummaryRead(ctx context.Context, userID int64, conversationID string, at int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSummaryRead", ctx, userID, conversationID, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSummaryRead indicates an expected call of MarkSummaryRead.
func (mr *MockSummaryRepoMockRecorder) MarkSummaryRead(ctx, userID, conversationID, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSummaryRead", reflect.TypeOf((*MockSummaryRepo)(nil).MarkSummaryRead), ctx, userID, conversationID, at)
}

// UpsertSummary mocks base method.
func (m *MockSummaryRepo) UpsertSummary(ctx context.Context, s *agent_session_entity.SessionSummary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSummary", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertSummary indicates an expected call of UpsertSummary.
func (mr *MockSummaryRepoMockRecorder) UpsertSummary(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSummary", reflect.TypeOf((*MockSummaryRepo)(nil).UpsertSummary), ctx, s)
}
