// Code generated by MockGen. DO NOT EDIT.
// Source: save.go
//
// Generated by this command:
//
//	mockgen -source save.go -destination mock_agent_session_repo/mock_save.go
//

// Package mock_agent_session_repo is a generated GoMock package.
package mock_agent_session_repo

import (
	context "context"
	reflect "reflect"

	agent_session_entity "github.com/agentre-hub/agentre-server/internal/model/entity/agent_session_entity"
	agent_session_repo "github.com/agentre-hub/agentre-server/internal/repository/agent_session_repo"
	gomock "go.uber.org/mock/gomock"
)

// MockSaveRepo is a mock of SaveRepo interface.
type MockSaveRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSaveRepoMockRecorder
	isgomock struct{}
}

// MockSaveRepoMockRecorder is the mock recorder for MockSaveRepo.
type MockSaveRepoMockRecorder struct {
	mock *MockSaveRepo
}

// NewMockSaveRepo creates a new mock instance.
func NewMockSaveRepo(ctrl *gomock.Controller) *MockSaveRepo {
	mock := &MockSaveRepo{ctrl: ctrl}
	mock.recorder = &MockSaveRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSaveRepo) EXPECT() *MockSaveRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSaveRepo) Delete(ctx context.Context, userID int64, peerFingerprint, peerSessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, peerFingerprint, peerSessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSaveRepoMockRecorder) Delete(ctx, userID, peerFingerprint, peerSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSaveRepo)(nil).Delete), ctx, userID, peerFingerprint, peerSessionID)
}

// FindByIdentity mocks base method.
func (m *MockSaveRepo) FindByIdentity(ctx context.Context, userID int64, peerFingerprint, peerSessionID string) (*agent_session_entity.SessionSave, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIdentity", ctx, userID, peerFingerprint, peerSessionID)
	ret0, _ := ret[0].(*agent_session_entity.SessionSave)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdentity indicates an expected call of FindByIdentity.
func (mr *MockSaveRepoMockRecorder) FindByIdentity(ctx, userID, peerFingerprint, peerSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdentity", reflect.TypeOf((*MockSaveRepo)(nil).FindByIdentity), ctx, userID, peerFingerprint, peerSessionID)
}

// ListByUser mocks base method.
func (m *MockSaveRepo) ListByUser(ctx context.Context, userID int64) ([]*agent_session_entity.SessionSave, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]*agent_session_entity.SessionSave)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockSaveRepoMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockSaveRepo)(nil).ListByUser), ctx, userID)
}

// ListMachines mocks base method.
func (m *MockSaveRepo) ListMachines(ctx context.Context) ([]agent_session_repo.Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMachines", ctx)
	ret0, _ := ret[0].([]agent_session_repo.Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMachines indicates an expected call of ListMachines.
func (mr *MockSaveRepoMockRecorder) ListMachines(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMachines", reflect.TypeOf((*MockSaveRepo)(nil).ListMachines), ctx)
}

// Save mocks base method.
func (m *MockSaveRepo) Save(ctx context.Context, f *agent_session_entity.SessionSave) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSaveRepoMockRecorder) Save(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSaveRepo)(nil).Save), ctx, f)
}
