// Code generated by MockGen. DO NOT EDIT.
// Source: journal_frame.go
//
// Generated by this command:
//
//	mockgen -source journal_frame.go -destination mock_agent_session_repo/mock_journal_frame.go
//

// Package mock_agent_session_repo is a generated GoMock package.
package mock_agent_session_repo

import (
	context "context"
	reflect "reflect"

	agent_session_entity "github.com/agentre-hub/agentre-server/internal/model/entity/agent_session_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockJournalFrameRepo is a mock of JournalFrameRepo interface.
type MockJournalFrameRepo struct {
	ctrl     *gomock.Controller
	recorder *MockJournalFrameRepoMockRecorder
	isgomock struct{}
}

// MockJournalFrameRepoMockRecorder is the mock recorder for MockJournalFrameRepo.
type MockJournalFrameRepoMockRecorder struct {
	mock *MockJournalFrameRepo
}

// NewMockJournalFrameRepo creates a new mock instance.
func NewMockJournalFrameRepo(ctrl *gomock.Controller) *MockJournalFrameRepo {
	mock := &MockJournalFrameRepo{ctrl: ctrl}
	mock.recorder = &MockJournalFrameRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJournalFrameRepo) EXPECT() *MockJournalFrameRepoMockRecorder {
	return m.recorder
}

// DeleteFrames mocks base method.
func (m *MockJournalFrameRepo) DeleteFrames(ctx context.Context, userID int64, peerFingerprint, peerSessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFrames", ctx, userID, peerFingerprint, peerSessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFrames indicates an expected call of DeleteFrames.
func (mr *MockJournalFrameRepoMockRecorder) DeleteFrames(ctx, userID, peerFingerprint, peerSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFrames", reflect.TypeOf((*MockJournalFrameRepo)(nil).DeleteFrames), ctx, userID, peerFingerprint, peerSessionID)
}

// ListFramesBefore mocks base method.
func (m *MockJournalFrameRepo) ListFramesBefore(ctx context.Context, userID int64, peerFingerprint, peerSessionID string, beforeSeq int64, limit int) ([]*agent_session_entity.JournalFrame, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFramesBefore", ctx, userID, peerFingerprint, peerSessionID, beforeSeq, limit)
	ret0, _ := ret[0].([]*agent_session_entity.JournalFrame)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFramesBefore indicates an expected call of ListFramesBefore.
func (mr *MockJournalFrameRepoMockRecorder) ListFramesBefore(ctx, userID, peerFingerprint, peerSessionID, beforeSeq, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFramesBefore", reflect.TypeOf((*MockJournalFrameRepo)(nil).ListFramesBefore), ctx, userID, peerFingerprint, peerSessionID, beforeSeq, limit)
}

// ListFramesBySeq mocks base method.
func (m *MockJournalFrameRepo) ListFramesBySeq(ctx context.Context, userID int64, peerFingerprint, peerSessionID string, fromSeq int64, limit int) ([]*agent_session_entity.JournalFrame, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFramesBySeq", ctx, userID, peerFingerprint, peerSessionID, fromSeq, limit)
	ret0, _ := ret[0].([]*agent_session_entity.JournalFrame)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFramesBySeq indicates an expected call of ListFramesBySeq.
func (mr *MockJournalFrameRepoMockRecorder) ListFramesBySeq(ctx, userID, peerFingerprint, peerSessionID, fromSeq, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFramesBySeq", reflect.TypeOf((*MockJournalFrameRepo)(nil).ListFramesBySeq), ctx, userID, peerFingerprint, peerSessionID, fromSeq, limit)
}

// WriteFrames mocks base method.
func (m *MockJournalFrameRepo) WriteFrames(ctx context.Context, frames []*agent_session_entity.JournalFrame) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFrames", ctx, frames)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFrames indicates an expected call of WriteFrames.
func (mr *MockJournalFrameRepoMockRecorder) WriteFrames(ctx, frames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFrames", reflect.TypeOf((*MockJournalFrameRepo)(nil).WriteFrames), ctx, frames)
}
