// Code generated by MockGen. DO NOT EDIT.
// Source: durable_frame.go
//
// Generated by this command:
//
//	mockgen -source durable_frame.go -destination mock_agent_session_repo/mock_durable_frame.go
//

// Package mock_agent_session_repo is a generated GoMock package.
package mock_agent_session_repo

import (
	context "context"
	reflect "reflect"

	agent_session_entity "github.com/agentre-hub/agentre-server/internal/model/entity/agent_session_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockDurableFrameRepo is a mock of DurableFrameRepo interface.
type MockDurableFrameRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDurableFrameRepoMockRecorder
	isgomock struct{}
}

// MockDurableFrameRepoMockRecorder is the mock recorder for MockDurableFrameRepo.
type MockDurableFrameRepoMockRecorder struct {
	mock *MockDurableFrameRepo
}

// NewMockDurableFrameRepo creates a new mock instance.
func NewMockDurableFrameRepo(ctrl *gomock.Controller) *MockDurableFrameRepo {
	mock := &MockDurableFrameRepo{ctrl: ctrl}
	mock.recorder = &MockDurableFrameRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDurableFrameRepo) EXPECT() *MockDurableFrameRepoMockRecorder {
	return m.recorder
}

// DeleteFrames mocks base method.
func (m *MockDurableFrameRepo) DeleteFrames(ctx context.Context, userID int64, conversationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFrames", ctx, userID, conversationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFrames indicates an expected call of DeleteFrames.
func (mr *MockDurableFrameRepoMockRecorder) DeleteFrames(ctx, userID, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFrames", reflect.TypeOf((*MockDurableFrameRepo)(nil).DeleteFrames), ctx, userID, conversationID)
}

// ListFramesBefore mocks base method.
func (m *MockDurableFrameRepo) ListFramesBefore(ctx context.Context, userID int64, conversationID string, beforeSeq int64, limit int) ([]*agent_session_entity.DurableFrame, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFramesBefore", ctx, userID, conversationID, beforeSeq, limit)
	ret0, _ := ret[0].([]*agent_session_entity.DurableFrame)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFramesBefore indicates an expected call of ListFramesBefore.
func (mr *MockDurableFrameRepoMockRecorder) ListFramesBefore(ctx, userID, conversationID, beforeSeq, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFramesBefore", reflect.TypeOf((*MockDurableFrameRepo)(nil).ListFramesBefore), ctx, userID, conversationID, beforeSeq, limit)
}

// ListFramesBySeq mocks base method.
func (m *MockDurableFrameRepo) ListFramesBySeq(ctx context.Context, userID int64, conversationID string, fromSeq int64, limit int) ([]*agent_session_entity.DurableFrame, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFramesBySeq", ctx, userID, conversationID, fromSeq, limit)
	ret0, _ := ret[0].([]*agent_session_entity.DurableFrame)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFramesBySeq indicates an expected call of ListFramesBySeq.
func (mr *MockDurableFrameRepoMockRecorder) ListFramesBySeq(ctx, userID, conversationID, fromSeq, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFramesBySeq", reflect.TypeOf((*MockDurableFrameRepo)(nil).ListFramesBySeq), ctx, userID, conversationID, fromSeq, limit)
}

// WriteFrames mocks base method.
func (m *MockDurableFrameRepo) WriteFrames(ctx context.Context, frames []*agent_session_entity.DurableFrame) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFrames", ctx, frames)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFrames indicates an expected call of WriteFrames.
func (mr *MockDurableFrameRepoMockRecorder) WriteFrames(ctx, frames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFrames", reflect.TypeOf((*MockDurableFrameRepo)(nil).WriteFrames), ctx, frames)
}
