// Code generated by MockGen. DO NOT EDIT.
// Source: delete_todo.go
//
// Generated by this command:
//
//	mockgen -source delete_todo.go -destination mock_agent_session_repo/mock_delete_todo.go
//

// Package mock_agent_session_repo is a generated GoMock package.
package mock_agent_session_repo

import (
	context "context"
	reflect "reflect"

	agent_session_entity "github.com/agentre-hub/agentre-server/internal/model/entity/agent_session_entity"
	agent_session_repo "github.com/agentre-hub/agentre-server/internal/repository/agent_session_repo"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteTodoRepo is a mock of DeleteTodoRepo interface.
type MockDeleteTodoRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteTodoRepoMockRecorder
	isgomock struct{}
}

// MockDeleteTodoRepoMockRecorder is the mock recorder for MockDeleteTodoRepo.
type MockDeleteTodoRepoMockRecorder struct {
	mock *MockDeleteTodoRepo
}

// NewMockDeleteTodoRepo creates a new mock instance.
func NewMockDeleteTodoRepo(ctrl *gomock.Controller) *MockDeleteTodoRepo {
	mock := &MockDeleteTodoRepo{ctrl: ctrl}
	mock.recorder = &MockDeleteTodoRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteTodoRepo) EXPECT() *MockDeleteTodoRepoMockRecorder {
	return m.recorder
}

// AddDeleteTodo mocks base method.
func (m *MockDeleteTodoRepo) AddDeleteTodo(ctx context.Context, t *agent_session_entity.DeleteTodo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDeleteTodo", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDeleteTodo indicates an expected call of AddDeleteTodo.
func (mr *MockDeleteTodoRepoMockRecorder) AddDeleteTodo(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDeleteTodo", reflect.TypeOf((*MockDeleteTodoRepo)(nil).AddDeleteTodo), ctx, t)
}

// ListDeleteTodosByDevice mocks base method.
func (m *MockDeleteTodoRepo) ListDeleteTodosByDevice(ctx context.Context, userID int64, deviceFingerprint string) ([]*agent_session_entity.DeleteTodo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeleteTodosByDevice", ctx, userID, deviceFingerprint)
	ret0, _ := ret[0].([]*agent_session_entity.DeleteTodo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeleteTodosByDevice indicates an expected call of ListDeleteTodosByDevice.
func (mr *MockDeleteTodoRepoMockRecorder) ListDeleteTodosByDevice(ctx, userID, deviceFingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeleteTodosByDevice", reflect.TypeOf((*MockDeleteTodoRepo)(nil).ListDeleteTodosByDevice), ctx, userID, deviceFingerprint)
}

// ListPendingMachines mocks base method.
func (m *MockDeleteTodoRepo) ListPendingMachines(ctx context.Context) ([]agent_session_repo.PendingMachine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingMachines", ctx)
	ret0, _ := ret[0].([]agent_session_repo.PendingMachine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingMachines indicates an expected call of ListPendingMachines.
func (mr *MockDeleteTodoRepoMockRecorder) ListPendingMachines(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingMachines", reflect.TypeOf((*MockDeleteTodoRepo)(nil).ListPendingMachines), ctx)
}

// RemoveDeleteTodo mocks base method.
func (m *MockDeleteTodoRepo) RemoveDeleteTodo(ctx context.Context, userID int64, conversationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDeleteTodo", ctx, userID, conversationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDeleteTodo indicates an expected call of RemoveDeleteTodo.
func (mr *MockDeleteTodoRepoMockRecorder) RemoveDeleteTodo(ctx, userID, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDeleteTodo", reflect.TypeOf((*MockDeleteTodoRepo)(nil).RemoveDeleteTodo), ctx, userID, conversationID)
}

// RemoveDeleteTodosByDevice mocks base method.
func (m *MockDeleteTodoRepo) RemoveDeleteTodosByDevice(ctx context.Context, userID int64, deviceFingerprint string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDeleteTodosByDevice", ctx, userID, deviceFingerprint)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDeleteTodosByDevice indicates an expected call of RemoveDeleteTodosByDevice.
func (mr *MockDeleteTodoRepoMockRecorder) RemoveDeleteTodosByDevice(ctx, userID, deviceFingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDeleteTodosByDevice", reflect.TypeOf((*MockDeleteTodoRepo)(nil).RemoveDeleteTodosByDevice), ctx, userID, deviceFingerprint)
}
