// Code generated by MockGen. DO NOT EDIT.
// Source: settings.go
//
// Generated by this command:
//
//	mockgen -source settings.go -destination mock_user_repo/mock_settings.go
//

// Package mock_user_repo is a generated GoMock package.
package mock_user_repo

import (
	context "context"
	reflect "reflect"

	user_entity "github.com/agentre-hub/agentre-server/internal/model/entity/user_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSettingsRepo is a mock of SettingsRepo interface.
type MockSettingsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsRepoMockRecorder
	isgomock struct{}
}

// MockSettingsRepoMockRecorder is the mock recorder for MockSettingsRepo.
type MockSettingsRepoMockRecorder struct {
	mock *MockSettingsRepo
}

// NewMockSettingsRepo creates a new mock instance.
func NewMockSettingsRepo(ctrl *gomock.Controller) *MockSettingsRepo {
	mock := &MockSettingsRepo{ctrl: ctrl}
	mock.recorder = &MockSettingsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsRepo) EXPECT() *MockSettingsRepoMockRecorder {
	return m.recorder
}

// ActivityStatsEnabledForUpdate mocks base method.
func (m *MockSettingsRepo) ActivityStatsEnabledForUpdate(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivityStatsEnabledForUpdate", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActivityStatsEnabledForUpdate indicates an expected call of ActivityStatsEnabledForUpdate.
func (mr *MockSettingsRepoMockRecorder) ActivityStatsEnabledForUpdate(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivityStatsEnabledForUpdate", reflect.TypeOf((*MockSettingsRepo)(nil).ActivityStatsEnabledForUpdate), ctx, userID)
}

// Get mocks base method.
func (m *MockSettingsRepo) Get(ctx context.Context, userID int64) (user_entity.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(user_entity.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSettingsRepoMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSettingsRepo)(nil).Get), ctx, userID)
}

// ListEnabledUserIDs mocks base method.
func (m *MockSettingsRepo) ListEnabledUserIDs(ctx context.Context) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledUserIDs", ctx)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabledUserIDs indicates an expected call of ListEnabledUserIDs.
func (mr *MockSettingsRepoMockRecorder) ListEnabledUserIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledUserIDs", reflect.TypeOf((*MockSettingsRepo)(nil).ListEnabledUserIDs), ctx)
}

// SetActivityStats mocks base method.
func (m *MockSettingsRepo) SetActivityStats(ctx context.Context, userID int64, enabled bool, backfillFrom string, nowMs int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActivityStats", ctx, userID, enabled, backfillFrom, nowMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActivityStats indicates an expected call of SetActivityStats.
func (mr *MockSettingsRepoMockRecorder) SetActivityStats(ctx, userID, enabled, backfillFrom, nowMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActivityStats", reflect.TypeOf((*MockSettingsRepo)(nil).SetActivityStats), ctx, userID, enabled, backfillFrom, nowMs)
}

// TouchActivityPull mocks base method.
func (m *MockSettingsRepo) TouchActivityPull(ctx context.Context, userID, nowMs int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchActivityPull", ctx, userID, nowMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchActivityPull indicates an expected call of TouchActivityPull.
func (mr *MockSettingsRepoMockRecorder) TouchActivityPull(ctx, userID, nowMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchActivityPull", reflect.TypeOf((*MockSettingsRepo)(nil).TouchActivityPull), ctx, userID, nowMs)
}
