// Code generated by MockGen. DO NOT EDIT.
// Source: device_token.go
//
// Generated by this command:
//
//	mockgen -source device_token.go -destination mock_device_token_repo/mock_device_token.go
//

// Package mock_device_token_repo is a generated GoMock package.
package mock_device_token_repo

import (
	device_token_entity "agentre-server/internal/model/entity/device_token_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeviceTokenRepo is a mock of DeviceTokenRepo interface.
type MockDeviceTokenRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceTokenRepoMockRecorder
	isgomock struct{}
}

// MockDeviceTokenRepoMockRecorder is the mock recorder for MockDeviceTokenRepo.
type MockDeviceTokenRepoMockRecorder struct {
	mock *MockDeviceTokenRepo
}

// NewMockDeviceTokenRepo creates a new mock instance.
func NewMockDeviceTokenRepo(ctrl *gomock.Controller) *MockDeviceTokenRepo {
	mock := &MockDeviceTokenRepo{ctrl: ctrl}
	mock.recorder = &MockDeviceTokenRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceTokenRepo) EXPECT() *MockDeviceTokenRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeviceTokenRepo) Create(ctx context.Context, e *device_token_entity.DeviceToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeviceTokenRepoMockRecorder) Create(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceTokenRepo)(nil).Create), ctx, e)
}

// DeleteRevokedBefore mocks base method.
func (m *MockDeviceTokenRepo) DeleteRevokedBefore(ctx context.Context, cutoffMs int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRevokedBefore", ctx, cutoffMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRevokedBefore indicates an expected call of DeleteRevokedBefore.
func (mr *MockDeviceTokenRepoMockRecorder) DeleteRevokedBefore(ctx, cutoffMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRevokedBefore", reflect.TypeOf((*MockDeviceTokenRepo)(nil).DeleteRevokedBefore), ctx, cutoffMs)
}

// FindByHash mocks base method.
func (m *MockDeviceTokenRepo) FindByHash(ctx context.Context, hash string) (*device_token_entity.DeviceToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHash", ctx, hash)
	ret0, _ := ret[0].(*device_token_entity.DeviceToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHash indicates an expected call of FindByHash.
func (mr *MockDeviceTokenRepoMockRecorder) FindByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHash", reflect.TypeOf((*MockDeviceTokenRepo)(nil).FindByHash), ctx, hash)
}

// Revoke mocks base method.
func (m *MockDeviceTokenRepo) Revoke(ctx context.Context, id, nowMs int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id, nowMs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revoke indicates an expected call of Revoke.
func (mr *MockDeviceTokenRepoMockRecorder) Revoke(ctx, id, nowMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockDeviceTokenRepo)(nil).Revoke), ctx, id, nowMs)
}

// RevokeChain mocks base method.
func (m *MockDeviceTokenRepo) RevokeChain(ctx context.Context, deviceID, nowMs int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeChain", ctx, deviceID, nowMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeChain indicates an expected call of RevokeChain.
func (mr *MockDeviceTokenRepoMockRecorder) RevokeChain(ctx, deviceID, nowMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeChain", reflect.TypeOf((*MockDeviceTokenRepo)(nil).RevokeChain), ctx, deviceID, nowMs)
}

// TouchLastUsed mocks base method.
func (m *MockDeviceTokenRepo) TouchLastUsed(ctx context.Context, id, nowMs int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchLastUsed", ctx, id, nowMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchLastUsed indicates an expected call of TouchLastUsed.
func (mr *MockDeviceTokenRepoMockRecorder) TouchLastUsed(ctx, id, nowMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchLastUsed", reflect.TypeOf((*MockDeviceTokenRepo)(nil).TouchLastUsed), ctx, id, nowMs)
}
