// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source ports.go -destination mock_ctl_svc/mock_ports.go
//

// Package mock_ctl_svc is a generated GoMock package.
package mock_ctl_svc

import (
	context "context"
	reflect "reflect"

	engine_svc "github.com/agentre-hub/agentre-server/internal/service/engine_svc"
	workspace_svc "github.com/agentre-hub/agentre-server/internal/service/workspace_svc"
	gomock "go.uber.org/mock/gomock"
)

// MockOrgWriter is a mock of OrgWriter interface.
type MockOrgWriter struct {
	ctrl     *gomock.Controller
	recorder *MockOrgWriterMockRecorder
	isgomock struct{}
}

// MockOrgWriterMockRecorder is the mock recorder for MockOrgWriter.
type MockOrgWriterMockRecorder struct {
	mock *MockOrgWriter
}

// NewMockOrgWriter creates a new mock instance.
func NewMockOrgWriter(ctrl *gomock.Controller) *MockOrgWriter {
	mock := &MockOrgWriter{ctrl: ctrl}
	mock.recorder = &MockOrgWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrgWriter) EXPECT() *MockOrgWriterMockRecorder {
	return m.recorder
}

// CreateOrgObject mocks base method.
func (m *MockOrgWriter) CreateOrgObject(ctx context.Context, in workspace_svc.OrgWriteInput) (*workspace_svc.OrgWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrgObject", ctx, in)
	ret0, _ := ret[0].(*workspace_svc.OrgWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrgObject indicates an expected call of CreateOrgObject.
func (mr *MockOrgWriterMockRecorder) CreateOrgObject(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrgObject", reflect.TypeOf((*MockOrgWriter)(nil).CreateOrgObject), ctx, in)
}

// DeleteOrgObject mocks base method.
func (m *MockOrgWriter) DeleteOrgObject(ctx context.Context, in workspace_svc.OrgWriteInput) (*workspace_svc.OrgWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrgObject", ctx, in)
	ret0, _ := ret[0].(*workspace_svc.OrgWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOrgObject indicates an expected call of DeleteOrgObject.
func (mr *MockOrgWriterMockRecorder) DeleteOrgObject(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrgObject", reflect.TypeOf((*MockOrgWriter)(nil).DeleteOrgObject), ctx, in)
}

// SetExecTargetOrder mocks base method.
func (m *MockOrgWriter) SetExecTargetOrder(ctx context.Context, in workspace_svc.SetExecTargetOrderInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetExecTargetOrder", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetExecTargetOrder indicates an expected call of SetExecTargetOrder.
func (mr *MockOrgWriterMockRecorder) SetExecTargetOrder(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExecTargetOrder", reflect.TypeOf((*MockOrgWriter)(nil).SetExecTargetOrder), ctx, in)
}

// SetProjectLocation mocks base method.
func (m *MockOrgWriter) SetProjectLocation(ctx context.Context, in workspace_svc.SetProjectLocationInput) (*workspace_svc.OrgWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProjectLocation", ctx, in)
	ret0, _ := ret[0].(*workspace_svc.OrgWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetProjectLocation indicates an expected call of SetProjectLocation.
func (mr *MockOrgWriterMockRecorder) SetProjectLocation(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProjectLocation", reflect.TypeOf((*MockOrgWriter)(nil).SetProjectLocation), ctx, in)
}

// UpdateOrgObject mocks base method.
func (m *MockOrgWriter) UpdateOrgObject(ctx context.Context, in workspace_svc.OrgWriteInput) (*workspace_svc.OrgWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrgObject", ctx, in)
	ret0, _ := ret[0].(*workspace_svc.OrgWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrgObject indicates an expected call of UpdateOrgObject.
func (mr *MockOrgWriterMockRecorder) UpdateOrgObject(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrgObject", reflect.TypeOf((*MockOrgWriter)(nil).UpdateOrgObject), ctx, in)
}

// MockEngineWriter is a mock of EngineWriter interface.
type MockEngineWriter struct {
	ctrl     *gomock.Controller
	recorder *MockEngineWriterMockRecorder
	isgomock struct{}
}

// MockEngineWriterMockRecorder is the mock recorder for MockEngineWriter.
type MockEngineWriterMockRecorder struct {
	mock *MockEngineWriter
}

// NewMockEngineWriter creates a new mock instance.
func NewMockEngineWriter(ctrl *gomock.Controller) *MockEngineWriter {
	mock := &MockEngineWriter{ctrl: ctrl}
	mock.recorder = &MockEngineWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngineWriter) EXPECT() *MockEngineWriterMockRecorder {
	return m.recorder
}

// CreateBackend mocks base method.
func (m *MockEngineWriter) CreateBackend(ctx context.Context, in engine_svc.BackendWriteInput) (*engine_svc.BackendView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBackend", ctx, in)
	ret0, _ := ret[0].(*engine_svc.BackendView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBackend indicates an expected call of CreateBackend.
func (mr *MockEngineWriterMockRecorder) CreateBackend(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBackend", reflect.TypeOf((*MockEngineWriter)(nil).CreateBackend), ctx, in)
}

// CreateProvider mocks base method.
func (m *MockEngineWriter) CreateProvider(ctx context.Context, in engine_svc.ProviderWriteInput) (*engine_svc.ProviderView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProvider", ctx, in)
	ret0, _ := ret[0].(*engine_svc.ProviderView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProvider indicates an expected call of CreateProvider.
func (mr *MockEngineWriterMockRecorder) CreateProvider(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProvider", reflect.TypeOf((*MockEngineWriter)(nil).CreateProvider), ctx, in)
}

// CreateProviderModel mocks base method.
func (m *MockEngineWriter) CreateProviderModel(ctx context.Context, in engine_svc.ModelWriteInput) (*engine_svc.ProviderView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProviderModel", ctx, in)
	ret0, _ := ret[0].(*engine_svc.ProviderView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProviderModel indicates an expected call of CreateProviderModel.
func (mr *MockEngineWriterMockRecorder) CreateProviderModel(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProviderModel", reflect.TypeOf((*MockEngineWriter)(nil).CreateProviderModel), ctx, in)
}

// DeleteBackend mocks base method.
func (m *MockEngineWriter) DeleteBackend(ctx context.Context, userID int64, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBackend", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBackend indicates an expected call of DeleteBackend.
func (mr *MockEngineWriterMockRecorder) DeleteBackend(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBackend", reflect.TypeOf((*MockEngineWriter)(nil).DeleteBackend), ctx, userID, id)
}

// DeleteProvider mocks base method.
func (m *MockEngineWriter) DeleteProvider(ctx context.Context, userID int64, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProvider", ctx, userID, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProvider indicates an expected call of DeleteProvider.
func (mr *MockEngineWriterMockRecorder) DeleteProvider(ctx, userID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProvider", reflect.TypeOf((*MockEngineWriter)(nil).DeleteProvider), ctx, userID, key)
}

// DeleteProviderModel mocks base method.
func (m *MockEngineWriter) DeleteProviderModel(ctx context.Context, userID int64, providerKey, modelKey string) (*engine_svc.ProviderView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProviderModel", ctx, userID, providerKey, modelKey)
	ret0, _ := ret[0].(*engine_svc.ProviderView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProviderModel indicates an expected call of DeleteProviderModel.
func (mr *MockEngineWriterMockRecorder) DeleteProviderModel(ctx, userID, providerKey, modelKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProviderModel", reflect.TypeOf((*MockEngineWriter)(nil).DeleteProviderModel), ctx, userID, providerKey, modelKey)
}

// UpdateBackend mocks base method.
func (m *MockEngineWriter) UpdateBackend(ctx context.Context, in engine_svc.BackendWriteInput) (*engine_svc.BackendView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBackend", ctx, in)
	ret0, _ := ret[0].(*engine_svc.BackendView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBackend indicates an expected call of UpdateBackend.
func (mr *MockEngineWriterMockRecorder) UpdateBackend(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBackend", reflect.TypeOf((*MockEngineWriter)(nil).UpdateBackend), ctx, in)
}

// UpdateProvider mocks base method.
func (m *MockEngineWriter) UpdateProvider(ctx context.Context, in engine_svc.ProviderWriteInput) (*engine_svc.ProviderView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProvider", ctx, in)
	ret0, _ := ret[0].(*engine_svc.ProviderView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProvider indicates an expected call of UpdateProvider.
func (mr *MockEngineWriterMockRecorder) UpdateProvider(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProvider", reflect.TypeOf((*MockEngineWriter)(nil).UpdateProvider), ctx, in)
}

// UpdateProviderModel mocks base method.
func (m *MockEngineWriter) UpdateProviderModel(ctx context.Context, in engine_svc.ModelWriteInput) (*engine_svc.ProviderView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProviderModel", ctx, in)
	ret0, _ := ret[0].(*engine_svc.ProviderView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProviderModel indicates an expected call of UpdateProviderModel.
func (mr *MockEngineWriterMockRecorder) UpdateProviderModel(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProviderModel", reflect.TypeOf((*MockEngineWriter)(nil).UpdateProviderModel), ctx, in)
}
