// Code generated by MockGen. DO NOT EDIT.
// Source: device.go
//
// Generated by this command:
//
//	mockgen -source device.go -destination mock_device_repo/mock_device.go
//

// Package mock_device_repo is a generated GoMock package.
package mock_device_repo

import (
	device_entity "agentre-hub/internal/model/entity/device_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeviceRepo is a mock of DeviceRepo interface.
type MockDeviceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceRepoMockRecorder
	isgomock struct{}
}

// MockDeviceRepoMockRecorder is the mock recorder for MockDeviceRepo.
type MockDeviceRepoMockRecorder struct {
	mock *MockDeviceRepo
}

// NewMockDeviceRepo creates a new mock instance.
func NewMockDeviceRepo(ctrl *gomock.Controller) *MockDeviceRepo {
	mock := &MockDeviceRepo{ctrl: ctrl}
	mock.recorder = &MockDeviceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceRepo) EXPECT() *MockDeviceRepoMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockDeviceRepo) Find(ctx context.Context, id int64) (*device_entity.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*device_entity.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockDeviceRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockDeviceRepo)(nil).Find), ctx, id)
}

// FindByFingerprint mocks base method.
func (m *MockDeviceRepo) FindByFingerprint(ctx context.Context, userID int64, fingerprint string) (*device_entity.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFingerprint", ctx, userID, fingerprint)
	ret0, _ := ret[0].(*device_entity.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFingerprint indicates an expected call of FindByFingerprint.
func (mr *MockDeviceRepoMockRecorder) FindByFingerprint(ctx, userID, fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFingerprint", reflect.TypeOf((*MockDeviceRepo)(nil).FindByFingerprint), ctx, userID, fingerprint)
}

// ListByUser mocks base method.
func (m *MockDeviceRepo) ListByUser(ctx context.Context, userID int64) ([]*device_entity.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]*device_entity.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockDeviceRepoMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockDeviceRepo)(nil).ListByUser), ctx, userID)
}

// Revoke mocks base method.
func (m *MockDeviceRepo) Revoke(ctx context.Context, id, nowMs int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id, nowMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockDeviceRepoMockRecorder) Revoke(ctx, id, nowMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockDeviceRepo)(nil).Revoke), ctx, id, nowMs)
}

// Touch mocks base method.
func (m *MockDeviceRepo) Touch(ctx context.Context, id, nowMs int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Touch", ctx, id, nowMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Touch indicates an expected call of Touch.
func (mr *MockDeviceRepoMockRecorder) Touch(ctx, id, nowMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Touch", reflect.TypeOf((*MockDeviceRepo)(nil).Touch), ctx, id, nowMs)
}

// Upsert mocks base method.
func (m *MockDeviceRepo) Upsert(ctx context.Context, d *device_entity.Device) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockDeviceRepoMockRecorder) Upsert(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockDeviceRepo)(nil).Upsert), ctx, d)
}
