// Code generated by MockGen. DO NOT EDIT.
// Source: object.go
//
// Generated by this command:
//
//	mockgen -source object.go -destination mock_sync_repo/mock_object.go
//

// Package mock_sync_repo is a generated GoMock package.
package mock_sync_repo

import (
	sync_entity "agentre-server/internal/model/entity/sync_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSyncObjectRepo is a mock of SyncObjectRepo interface.
type MockSyncObjectRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSyncObjectRepoMockRecorder
	isgomock struct{}
}

// MockSyncObjectRepoMockRecorder is the mock recorder for MockSyncObjectRepo.
type MockSyncObjectRepoMockRecorder struct {
	mock *MockSyncObjectRepo
}

// NewMockSyncObjectRepo creates a new mock instance.
func NewMockSyncObjectRepo(ctrl *gomock.Controller) *MockSyncObjectRepo {
	mock := &MockSyncObjectRepo{ctrl: ctrl}
	mock.recorder = &MockSyncObjectRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncObjectRepo) EXPECT() *MockSyncObjectRepoMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockSyncObjectRepo) Find(ctx context.Context, userID int64, syncID string) (*sync_entity.SyncObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, userID, syncID)
	ret0, _ := ret[0].(*sync_entity.SyncObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockSyncObjectRepoMockRecorder) Find(ctx, userID, syncID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockSyncObjectRepo)(nil).Find), ctx, userID, syncID)
}

// FindLocationByNaturalKey mocks base method.
func (m *MockSyncObjectRepo) FindLocationByNaturalKey(ctx context.Context, userID int64, projectSyncID, fingerprint string) (*sync_entity.SyncObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLocationByNaturalKey", ctx, userID, projectSyncID, fingerprint)
	ret0, _ := ret[0].(*sync_entity.SyncObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLocationByNaturalKey indicates an expected call of FindLocationByNaturalKey.
func (mr *MockSyncObjectRepoMockRecorder) FindLocationByNaturalKey(ctx, userID, projectSyncID, fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLocationByNaturalKey", reflect.TypeOf((*MockSyncObjectRepo)(nil).FindLocationByNaturalKey), ctx, userID, projectSyncID, fingerprint)
}

// ListSince mocks base method.
func (m *MockSyncObjectRepo) ListSince(ctx context.Context, userID, cursor int64, limit int) ([]*sync_entity.SyncObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSince", ctx, userID, cursor, limit)
	ret0, _ := ret[0].([]*sync_entity.SyncObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSince indicates an expected call of ListSince.
func (mr *MockSyncObjectRepoMockRecorder) ListSince(ctx, userID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSince", reflect.TypeOf((*MockSyncObjectRepo)(nil).ListSince), ctx, userID, cursor, limit)
}

// Save mocks base method.
func (m *MockSyncObjectRepo) Save(ctx context.Context, obj *sync_entity.SyncObject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSyncObjectRepoMockRecorder) Save(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSyncObjectRepo)(nil).Save), ctx, obj)
}

// Tombstone mocks base method.
func (m *MockSyncObjectRepo) Tombstone(ctx context.Context, id, version, nowMs int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tombstone", ctx, id, version, nowMs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tombstone indicates an expected call of Tombstone.
func (mr *MockSyncObjectRepoMockRecorder) Tombstone(ctx, id, version, nowMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tombstone", reflect.TypeOf((*MockSyncObjectRepo)(nil).Tombstone), ctx, id, version, nowMs)
}
