// Code generated by MockGen. DO NOT EDIT.
// Source: avatar.go
//
// Generated by this command:
//
//	mockgen -source avatar.go -destination mock_sync_repo/mock_avatar.go
//

// Package mock_sync_repo is a generated GoMock package.
package mock_sync_repo

import (
	context "context"
	sync_entity "github.com/agentre-hub/agentre-server/internal/model/entity/sync_entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSyncAvatarRepo is a mock of SyncAvatarRepo interface.
type MockSyncAvatarRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSyncAvatarRepoMockRecorder
	isgomock struct{}
}

// MockSyncAvatarRepoMockRecorder is the mock recorder for MockSyncAvatarRepo.
type MockSyncAvatarRepoMockRecorder struct {
	mock *MockSyncAvatarRepo
}

// NewMockSyncAvatarRepo creates a new mock instance.
func NewMockSyncAvatarRepo(ctrl *gomock.Controller) *MockSyncAvatarRepo {
	mock := &MockSyncAvatarRepo{ctrl: ctrl}
	mock.recorder = &MockSyncAvatarRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncAvatarRepo) EXPECT() *MockSyncAvatarRepoMockRecorder {
	return m.recorder
}

// DeleteUnreferencedBefore mocks base method.
func (m *MockSyncAvatarRepo) DeleteUnreferencedBefore(ctx context.Context, cutoff int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUnreferencedBefore", ctx, cutoff)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUnreferencedBefore indicates an expected call of DeleteUnreferencedBefore.
func (mr *MockSyncAvatarRepoMockRecorder) DeleteUnreferencedBefore(ctx, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUnreferencedBefore", reflect.TypeOf((*MockSyncAvatarRepo)(nil).DeleteUnreferencedBefore), ctx, cutoff)
}

// Find mocks base method.
func (m *MockSyncAvatarRepo) Find(ctx context.Context, userID int64, contentHash string) (*sync_entity.SyncAvatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, userID, contentHash)
	ret0, _ := ret[0].(*sync_entity.SyncAvatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockSyncAvatarRepoMockRecorder) Find(ctx, userID, contentHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockSyncAvatarRepo)(nil).Find), ctx, userID, contentHash)
}

// Save mocks base method.
func (m *MockSyncAvatarRepo) Save(ctx context.Context, a *sync_entity.SyncAvatar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSyncAvatarRepoMockRecorder) Save(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSyncAvatarRepo)(nil).Save), ctx, a)
}
