// Code generated by MockGen. DO NOT EDIT.
// Source: local_path.go
//
// Generated by this command:
//
//	mockgen -source local_path.go -destination mock_sync_repo/mock_local_path.go
//

// Package mock_sync_repo is a generated GoMock package.
package mock_sync_repo

import (
	sync_entity "agentre-server/internal/model/entity/sync_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSyncLocalPathRepo is a mock of SyncLocalPathRepo interface.
type MockSyncLocalPathRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSyncLocalPathRepoMockRecorder
	isgomock struct{}
}

// MockSyncLocalPathRepoMockRecorder is the mock recorder for MockSyncLocalPathRepo.
type MockSyncLocalPathRepoMockRecorder struct {
	mock *MockSyncLocalPathRepo
}

// NewMockSyncLocalPathRepo creates a new mock instance.
func NewMockSyncLocalPathRepo(ctrl *gomock.Controller) *MockSyncLocalPathRepo {
	mock := &MockSyncLocalPathRepo{ctrl: ctrl}
	mock.recorder = &MockSyncLocalPathRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncLocalPathRepo) EXPECT() *MockSyncLocalPathRepoMockRecorder {
	return m.recorder
}

// ReplaceSnapshot mocks base method.
func (m *MockSyncLocalPathRepo) ReplaceSnapshot(ctx context.Context, userID, deviceID int64, items []*sync_entity.DeviceLocalPath) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceSnapshot", ctx, userID, deviceID, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceSnapshot indicates an expected call of ReplaceSnapshot.
func (mr *MockSyncLocalPathRepoMockRecorder) ReplaceSnapshot(ctx, userID, deviceID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceSnapshot", reflect.TypeOf((*MockSyncLocalPathRepo)(nil).ReplaceSnapshot), ctx, userID, deviceID, items)
}
