// Code generated by MockGen. DO NOT EDIT.
// Source: local_path.go
//
// Generated by this command:
//
//	mockgen -source local_path.go -destination mock_sync_repo/mock_local_path.go
//

// Package mock_sync_repo is a generated GoMock package.
package mock_sync_repo

import (
	sync_entity "agentre-server/internal/model/entity/sync_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSyncLocalPathRepo is a mock of SyncLocalPathRepo interface.
type MockSyncLocalPathRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSyncLocalPathRepoMockRecorder
	isgomock struct{}
}

// MockSyncLocalPathRepoMockRecorder is the mock recorder for MockSyncLocalPathRepo.
type MockSyncLocalPathRepoMockRecorder struct {
	mock *MockSyncLocalPathRepo
}

// NewMockSyncLocalPathRepo creates a new mock instance.
func NewMockSyncLocalPathRepo(ctrl *gomock.Controller) *MockSyncLocalPathRepo {
	mock := &MockSyncLocalPathRepo{ctrl: ctrl}
	mock.recorder = &MockSyncLocalPathRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncLocalPathRepo) EXPECT() *MockSyncLocalPathRepoMockRecorder {
	return m.recorder
}

// DeleteByDevice mocks base method.
func (m *MockSyncLocalPathRepo) DeleteByDevice(ctx context.Context, deviceID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByDevice", ctx, deviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByDevice indicates an expected call of DeleteByDevice.
func (mr *MockSyncLocalPathRepoMockRecorder) DeleteByDevice(ctx, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByDevice", reflect.TypeOf((*MockSyncLocalPathRepo)(nil).DeleteByDevice), ctx, deviceID)
}

// ListByDevice mocks base method.
func (m *MockSyncLocalPathRepo) ListByDevice(ctx context.Context, userID, deviceID int64) ([]*sync_entity.DeviceLocalPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDevice", ctx, userID, deviceID)
	ret0, _ := ret[0].([]*sync_entity.DeviceLocalPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByDevice indicates an expected call of ListByDevice.
func (mr *MockSyncLocalPathRepoMockRecorder) ListByDevice(ctx, userID, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDevice", reflect.TypeOf((*MockSyncLocalPathRepo)(nil).ListByDevice), ctx, userID, deviceID)
}

// ReplaceSnapshot mocks base method.
func (m *MockSyncLocalPathRepo) ReplaceSnapshot(ctx context.Context, userID, deviceID int64, items []*sync_entity.DeviceLocalPath) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceSnapshot", ctx, userID, deviceID, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceSnapshot indicates an expected call of ReplaceSnapshot.
func (mr *MockSyncLocalPathRepoMockRecorder) ReplaceSnapshot(ctx, userID, deviceID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceSnapshot", reflect.TypeOf((*MockSyncLocalPathRepo)(nil).ReplaceSnapshot), ctx, userID, deviceID, items)
}
