// Code generated by MockGen. DO NOT EDIT.
// Source: state.go
//
// Generated by this command:
//
//	mockgen -source state.go -destination mock_sync_repo/mock_state.go
//

// Package mock_sync_repo is a generated GoMock package.
package mock_sync_repo

import (
	context "context"
	sync_entity "github.com/agentre-hub/agentre-server/internal/model/entity/sync_entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSyncStateRepo is a mock of SyncStateRepo interface.
type MockSyncStateRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSyncStateRepoMockRecorder
	isgomock struct{}
}

// MockSyncStateRepoMockRecorder is the mock recorder for MockSyncStateRepo.
type MockSyncStateRepoMockRecorder struct {
	mock *MockSyncStateRepo
}

// NewMockSyncStateRepo creates a new mock instance.
func NewMockSyncStateRepo(ctrl *gomock.Controller) *MockSyncStateRepo {
	mock := &MockSyncStateRepo{ctrl: ctrl}
	mock.recorder = &MockSyncStateRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncStateRepo) EXPECT() *MockSyncStateRepoMockRecorder {
	return m.recorder
}

// CurrentVersion mocks base method.
func (m *MockSyncStateRepo) CurrentVersion(ctx context.Context, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentVersion", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentVersion indicates an expected call of CurrentVersion.
func (mr *MockSyncStateRepoMockRecorder) CurrentVersion(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentVersion", reflect.TypeOf((*MockSyncStateRepo)(nil).CurrentVersion), ctx, userID)
}

// FindDeviceState mocks base method.
func (m *MockSyncStateRepo) FindDeviceState(ctx context.Context, userID, deviceID int64) (*sync_entity.DeviceSyncState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDeviceState", ctx, userID, deviceID)
	ret0, _ := ret[0].(*sync_entity.DeviceSyncState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDeviceState indicates an expected call of FindDeviceState.
func (mr *MockSyncStateRepoMockRecorder) FindDeviceState(ctx, userID, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDeviceState", reflect.TypeOf((*MockSyncStateRepo)(nil).FindDeviceState), ctx, userID, deviceID)
}

// NextVersion mocks base method.
func (m *MockSyncStateRepo) NextVersion(ctx context.Context, userID, n int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextVersion", ctx, userID, n)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextVersion indicates an expected call of NextVersion.
func (mr *MockSyncStateRepoMockRecorder) NextVersion(ctx, userID, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextVersion", reflect.TypeOf((*MockSyncStateRepo)(nil).NextVersion), ctx, userID, n)
}

// TouchDeviceState mocks base method.
func (m *MockSyncStateRepo) TouchDeviceState(ctx context.Context, userID, deviceID, nowMs int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchDeviceState", ctx, userID, deviceID, nowMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchDeviceState indicates an expected call of TouchDeviceState.
func (mr *MockSyncStateRepoMockRecorder) TouchDeviceState(ctx, userID, deviceID, nowMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchDeviceState", reflect.TypeOf((*MockSyncStateRepo)(nil).TouchDeviceState), ctx, userID, deviceID, nowMs)
}
