// Code generated by MockGen. DO NOT EDIT.
// Source: follow.go
//
// Generated by this command:
//
//	mockgen -source follow.go -destination mock_follow_repo/mock_follow.go
//

// Package mock_follow_repo is a generated GoMock package.
package mock_follow_repo

import (
	follow_entity "agentre-server/internal/model/entity/follow_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFollowRepo is a mock of FollowRepo interface.
type MockFollowRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFollowRepoMockRecorder
	isgomock struct{}
}

// MockFollowRepoMockRecorder is the mock recorder for MockFollowRepo.
type MockFollowRepoMockRecorder struct {
	mock *MockFollowRepo
}

// NewMockFollowRepo creates a new mock instance.
func NewMockFollowRepo(ctrl *gomock.Controller) *MockFollowRepo {
	mock := &MockFollowRepo{ctrl: ctrl}
	mock.recorder = &MockFollowRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowRepo) EXPECT() *MockFollowRepoMockRecorder {
	return m.recorder
}

// Follow mocks base method.
func (m *MockFollowRepo) Follow(ctx context.Context, f *follow_entity.FollowedSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// Follow indicates an expected call of Follow.
func (mr *MockFollowRepoMockRecorder) Follow(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockFollowRepo)(nil).Follow), ctx, f)
}

// ListByUser mocks base method.
func (m *MockFollowRepo) ListByUser(ctx context.Context, userID int64) ([]*follow_entity.FollowedSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]*follow_entity.FollowedSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockFollowRepoMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockFollowRepo)(nil).ListByUser), ctx, userID)
}

// Unfollow mocks base method.
func (m *MockFollowRepo) Unfollow(ctx context.Context, userID int64, deviceFingerprint, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfollow", ctx, userID, deviceFingerprint, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unfollow indicates an expected call of Unfollow.
func (mr *MockFollowRepoMockRecorder) Unfollow(ctx, userID, deviceFingerprint, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfollow", reflect.TypeOf((*MockFollowRepo)(nil).Unfollow), ctx, userID, deviceFingerprint, sessionID)
}
