// Code generated by MockGen. DO NOT EDIT.
// Source: webauthn_credential.go
//
// Generated by this command:
//
//	mockgen -source webauthn_credential.go -destination mock_webauthn_credential_repo/mock_webauthn_credential.go
//

// Package mock_webauthn_credential_repo is a generated GoMock package.
package mock_webauthn_credential_repo

import (
	context "context"
	webauthn_credential_entity "github.com/agentre-hub/agentre-server/internal/model/entity/webauthn_credential_entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWebAuthnCredentialRepo is a mock of WebAuthnCredentialRepo interface.
type MockWebAuthnCredentialRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWebAuthnCredentialRepoMockRecorder
	isgomock struct{}
}

// MockWebAuthnCredentialRepoMockRecorder is the mock recorder for MockWebAuthnCredentialRepo.
type MockWebAuthnCredentialRepoMockRecorder struct {
	mock *MockWebAuthnCredentialRepo
}

// NewMockWebAuthnCredentialRepo creates a new mock instance.
func NewMockWebAuthnCredentialRepo(ctrl *gomock.Controller) *MockWebAuthnCredentialRepo {
	mock := &MockWebAuthnCredentialRepo{ctrl: ctrl}
	mock.recorder = &MockWebAuthnCredentialRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebAuthnCredentialRepo) EXPECT() *MockWebAuthnCredentialRepoMockRecorder {
	return m.recorder
}

// CountByUser mocks base method.
func (m *MockWebAuthnCredentialRepo) CountByUser(ctx context.Context, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUser", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUser indicates an expected call of CountByUser.
func (mr *MockWebAuthnCredentialRepoMockRecorder) CountByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUser", reflect.TypeOf((*MockWebAuthnCredentialRepo)(nil).CountByUser), ctx, userID)
}

// Create mocks base method.
func (m *MockWebAuthnCredentialRepo) Create(ctx context.Context, c *webauthn_credential_entity.WebAuthnCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWebAuthnCredentialRepoMockRecorder) Create(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWebAuthnCredentialRepo)(nil).Create), ctx, c)
}

// DeleteByUser mocks base method.
func (m *MockWebAuthnCredentialRepo) DeleteByUser(ctx context.Context, userID, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUser", ctx, userID, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByUser indicates an expected call of DeleteByUser.
func (mr *MockWebAuthnCredentialRepoMockRecorder) DeleteByUser(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUser", reflect.TypeOf((*MockWebAuthnCredentialRepo)(nil).DeleteByUser), ctx, userID, id)
}

// FindByCredentialID mocks base method.
func (m *MockWebAuthnCredentialRepo) FindByCredentialID(ctx context.Context, credentialID []byte) (*webauthn_credential_entity.WebAuthnCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCredentialID", ctx, credentialID)
	ret0, _ := ret[0].(*webauthn_credential_entity.WebAuthnCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCredentialID indicates an expected call of FindByCredentialID.
func (mr *MockWebAuthnCredentialRepoMockRecorder) FindByCredentialID(ctx, credentialID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCredentialID", reflect.TypeOf((*MockWebAuthnCredentialRepo)(nil).FindByCredentialID), ctx, credentialID)
}

// ListByUser mocks base method.
func (m *MockWebAuthnCredentialRepo) ListByUser(ctx context.Context, userID int64) ([]*webauthn_credential_entity.WebAuthnCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]*webauthn_credential_entity.WebAuthnCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockWebAuthnCredentialRepoMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockWebAuthnCredentialRepo)(nil).ListByUser), ctx, userID)
}

// TouchUsage mocks base method.
func (m *MockWebAuthnCredentialRepo) TouchUsage(ctx context.Context, id int64, signCount uint32, usedAt int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchUsage", ctx, id, signCount, usedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchUsage indicates an expected call of TouchUsage.
func (mr *MockWebAuthnCredentialRepoMockRecorder) TouchUsage(ctx, id, signCount, usedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchUsage", reflect.TypeOf((*MockWebAuthnCredentialRepo)(nil).TouchUsage), ctx, id, signCount, usedAt)
}
