// Code generated by MockGen. DO NOT EDIT.
// Source: daily.go
//
// Generated by this command:
//
//	mockgen -source daily.go -destination mock_activity_repo/mock_daily.go
//

// Package mock_activity_repo is a generated GoMock package.
package mock_activity_repo

import (
	context "context"
	reflect "reflect"

	activity_entity "github.com/agentre-hub/agentre-server/internal/model/entity/activity_entity"
	activity_repo "github.com/agentre-hub/agentre-server/internal/repository/activity_repo"
	gomock "go.uber.org/mock/gomock"
)

// MockDailyRepo is a mock of DailyRepo interface.
type MockDailyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDailyRepoMockRecorder
	isgomock struct{}
}

// MockDailyRepoMockRecorder is the mock recorder for MockDailyRepo.
type MockDailyRepoMockRecorder struct {
	mock *MockDailyRepo
}

// NewMockDailyRepo creates a new mock instance.
func NewMockDailyRepo(ctrl *gomock.Controller) *MockDailyRepo {
	mock := &MockDailyRepo{ctrl: ctrl}
	mock.recorder = &MockDailyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDailyRepo) EXPECT() *MockDailyRepoMockRecorder {
	return m.recorder
}

// DeleteByUser mocks base method.
func (m *MockDailyRepo) DeleteByUser(ctx context.Context, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUser", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByUser indicates an expected call of DeleteByUser.
func (mr *MockDailyRepoMockRecorder) DeleteByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUser", reflect.TypeOf((*MockDailyRepo)(nil).DeleteByUser), ctx, userID)
}

// LatestDay mocks base method.
func (m *MockDailyRepo) LatestDay(ctx context.Context, userID int64, peerFingerprint string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestDay", ctx, userID, peerFingerprint)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestDay indicates an expected call of LatestDay.
func (mr *MockDailyRepoMockRecorder) LatestDay(ctx, userID, peerFingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestDay", reflect.TypeOf((*MockDailyRepo)(nil).LatestDay), ctx, userID, peerFingerprint)
}

// ReplaceBucketsFrom mocks base method.
func (m *MockDailyRepo) ReplaceBucketsFrom(ctx context.Context, userID int64, peerFingerprint, sinceDay string, buckets []*activity_entity.DailyBucket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceBucketsFrom", ctx, userID, peerFingerprint, sinceDay, buckets)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceBucketsFrom indicates an expected call of ReplaceBucketsFrom.
func (mr *MockDailyRepoMockRecorder) ReplaceBucketsFrom(ctx, userID, peerFingerprint, sinceDay, buckets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceBucketsFrom", reflect.TypeOf((*MockDailyRepo)(nil).ReplaceBucketsFrom), ctx, userID, peerFingerprint, sinceDay, buckets)
}

// SumByDims mocks base method.
func (m *MockDailyRepo) SumByDims(ctx context.Context, q activity_repo.DailyQuery, dims ...activity_repo.Dim) ([]activity_repo.DimSum, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, q}
	for _, a := range dims {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SumByDims", varargs...)
	ret0, _ := ret[0].([]activity_repo.DimSum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumByDims indicates an expected call of SumByDims.
func (mr *MockDailyRepoMockRecorder) SumByDims(ctx, q any, dims ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, q}, dims...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumByDims", reflect.TypeOf((*MockDailyRepo)(nil).SumByDims), varargs...)
}

// SumTotal mocks base method.
func (m *MockDailyRepo) SumTotal(ctx context.Context, q activity_repo.DailyQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumTotal", ctx, q)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumTotal indicates an expected call of SumTotal.
func (mr *MockDailyRepoMockRecorder) SumTotal(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumTotal", reflect.TypeOf((*MockDailyRepo)(nil).SumTotal), ctx, q)
}
