// Code generated by MockGen. DO NOT EDIT.
// Source: exec_order.go
//
// Generated by this command:
//
//	mockgen -source exec_order.go -destination mock_exec_order_repo/mock_exec_order.go
//

// Package mock_exec_order_repo is a generated GoMock package.
package mock_exec_order_repo

import (
	exec_order_entity "agentre-server/internal/model/entity/exec_order_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExecOrderRepo is a mock of ExecOrderRepo interface.
type MockExecOrderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockExecOrderRepoMockRecorder
	isgomock struct{}
}

// MockExecOrderRepoMockRecorder is the mock recorder for MockExecOrderRepo.
type MockExecOrderRepoMockRecorder struct {
	mock *MockExecOrderRepo
}

// NewMockExecOrderRepo creates a new mock instance.
func NewMockExecOrderRepo(ctrl *gomock.Controller) *MockExecOrderRepo {
	mock := &MockExecOrderRepo{ctrl: ctrl}
	mock.recorder = &MockExecOrderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecOrderRepo) EXPECT() *MockExecOrderRepoMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockExecOrderRepo) Find(ctx context.Context, userID int64, clientID, agentSyncID string) (*exec_order_entity.DeviceExecTargetOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, userID, clientID, agentSyncID)
	ret0, _ := ret[0].(*exec_order_entity.DeviceExecTargetOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockExecOrderRepoMockRecorder) Find(ctx, userID, clientID, agentSyncID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockExecOrderRepo)(nil).Find), ctx, userID, clientID, agentSyncID)
}

// ListByClient mocks base method.
func (m *MockExecOrderRepo) ListByClient(ctx context.Context, userID int64, clientID string) ([]*exec_order_entity.DeviceExecTargetOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClient", ctx, userID, clientID)
	ret0, _ := ret[0].([]*exec_order_entity.DeviceExecTargetOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClient indicates an expected call of ListByClient.
func (mr *MockExecOrderRepoMockRecorder) ListByClient(ctx, userID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClient", reflect.TypeOf((*MockExecOrderRepo)(nil).ListByClient), ctx, userID, clientID)
}

// Save mocks base method.
func (m *MockExecOrderRepo) Save(ctx context.Context, o *exec_order_entity.DeviceExecTargetOrder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockExecOrderRepoMockRecorder) Save(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockExecOrderRepo)(nil).Save), ctx, o)
}
