// Code generated by MockGen. DO NOT EDIT.
// Source: device_flow.go
//
// Generated by this command:
//
//	mockgen -source device_flow.go -destination mock_device_flow_repo/mock_device_flow.go
//

// Package mock_device_flow_repo is a generated GoMock package.
package mock_device_flow_repo

import (
	device_flow_entity "agentre-hub/internal/model/entity/device_flow_entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeviceFlowRepo is a mock of DeviceFlowRepo interface.
type MockDeviceFlowRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceFlowRepoMockRecorder
	isgomock struct{}
}

// MockDeviceFlowRepoMockRecorder is the mock recorder for MockDeviceFlowRepo.
type MockDeviceFlowRepoMockRecorder struct {
	mock *MockDeviceFlowRepo
}

// NewMockDeviceFlowRepo creates a new mock instance.
func NewMockDeviceFlowRepo(ctrl *gomock.Controller) *MockDeviceFlowRepo {
	mock := &MockDeviceFlowRepo{ctrl: ctrl}
	mock.recorder = &MockDeviceFlowRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceFlowRepo) EXPECT() *MockDeviceFlowRepoMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockDeviceFlowRepo) Approve(ctx context.Context, userCode string, userID, nowMs int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", ctx, userCode, userID, nowMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Approve indicates an expected call of Approve.
func (mr *MockDeviceFlowRepoMockRecorder) Approve(ctx, userCode, userID, nowMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockDeviceFlowRepo)(nil).Approve), ctx, userCode, userID, nowMs)
}

// Create mocks base method.
func (m *MockDeviceFlowRepo) Create(ctx context.Context, e *device_flow_entity.DeviceFlowCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeviceFlowRepoMockRecorder) Create(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceFlowRepo)(nil).Create), ctx, e)
}

// DeleteExpiredBefore mocks base method.
func (m *MockDeviceFlowRepo) DeleteExpiredBefore(ctx context.Context, cutoffMs int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredBefore", ctx, cutoffMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredBefore indicates an expected call of DeleteExpiredBefore.
func (mr *MockDeviceFlowRepoMockRecorder) DeleteExpiredBefore(ctx, cutoffMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredBefore", reflect.TypeOf((*MockDeviceFlowRepo)(nil).DeleteExpiredBefore), ctx, cutoffMs)
}

// Deny mocks base method.
func (m *MockDeviceFlowRepo) Deny(ctx context.Context, userCode string, nowMs int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deny", ctx, userCode, nowMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deny indicates an expected call of Deny.
func (mr *MockDeviceFlowRepoMockRecorder) Deny(ctx, userCode, nowMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deny", reflect.TypeOf((*MockDeviceFlowRepo)(nil).Deny), ctx, userCode, nowMs)
}

// FindByDeviceCode mocks base method.
func (m *MockDeviceFlowRepo) FindByDeviceCode(ctx context.Context, deviceCode string) (*device_flow_entity.DeviceFlowCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDeviceCode", ctx, deviceCode)
	ret0, _ := ret[0].(*device_flow_entity.DeviceFlowCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDeviceCode indicates an expected call of FindByDeviceCode.
func (mr *MockDeviceFlowRepoMockRecorder) FindByDeviceCode(ctx, deviceCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDeviceCode", reflect.TypeOf((*MockDeviceFlowRepo)(nil).FindByDeviceCode), ctx, deviceCode)
}

// FindPendingByUserCode mocks base method.
func (m *MockDeviceFlowRepo) FindPendingByUserCode(ctx context.Context, userCode string) (*device_flow_entity.DeviceFlowCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingByUserCode", ctx, userCode)
	ret0, _ := ret[0].(*device_flow_entity.DeviceFlowCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingByUserCode indicates an expected call of FindPendingByUserCode.
func (mr *MockDeviceFlowRepoMockRecorder) FindPendingByUserCode(ctx, userCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingByUserCode", reflect.TypeOf((*MockDeviceFlowRepo)(nil).FindPendingByUserCode), ctx, userCode)
}

// MarkConsumed mocks base method.
func (m *MockDeviceFlowRepo) MarkConsumed(ctx context.Context, deviceCode string, nowMs int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkConsumed", ctx, deviceCode, nowMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkConsumed indicates an expected call of MarkConsumed.
func (mr *MockDeviceFlowRepoMockRecorder) MarkConsumed(ctx, deviceCode, nowMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkConsumed", reflect.TypeOf((*MockDeviceFlowRepo)(nil).MarkConsumed), ctx, deviceCode, nowMs)
}

// UpdateLastPolled mocks base method.
func (m *MockDeviceFlowRepo) UpdateLastPolled(ctx context.Context, deviceCode string, nowMs int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastPolled", ctx, deviceCode, nowMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastPolled indicates an expected call of UpdateLastPolled.
func (mr *MockDeviceFlowRepoMockRecorder) UpdateLastPolled(ctx, deviceCode, nowMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastPolled", reflect.TypeOf((*MockDeviceFlowRepo)(nil).UpdateLastPolled), ctx, deviceCode, nowMs)
}
