// Code generated by MockGen. DO NOT EDIT.
// Source: user_identity.go
//
// Generated by this command:
//
//	mockgen -source user_identity.go -destination mock_user_identity_repo/mock_user_identity.go
//

// Package mock_user_identity_repo is a generated GoMock package.
package mock_user_identity_repo

import (
	context "context"
	user_identity_entity "github.com/agentre-hub/agentre-server/internal/model/entity/user_identity_entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserIdentityRepo is a mock of UserIdentityRepo interface.
type MockUserIdentityRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserIdentityRepoMockRecorder
	isgomock struct{}
}

// MockUserIdentityRepoMockRecorder is the mock recorder for MockUserIdentityRepo.
type MockUserIdentityRepoMockRecorder struct {
	mock *MockUserIdentityRepo
}

// NewMockUserIdentityRepo creates a new mock instance.
func NewMockUserIdentityRepo(ctrl *gomock.Controller) *MockUserIdentityRepo {
	mock := &MockUserIdentityRepo{ctrl: ctrl}
	mock.recorder = &MockUserIdentityRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserIdentityRepo) EXPECT() *MockUserIdentityRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserIdentityRepo) Create(ctx context.Context, e *user_identity_entity.UserIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserIdentityRepoMockRecorder) Create(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserIdentityRepo)(nil).Create), ctx, e)
}

// FindByProviderUID mocks base method.
func (m *MockUserIdentityRepo) FindByProviderUID(ctx context.Context, provider, providerUID string) (*user_identity_entity.UserIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProviderUID", ctx, provider, providerUID)
	ret0, _ := ret[0].(*user_identity_entity.UserIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProviderUID indicates an expected call of FindByProviderUID.
func (mr *MockUserIdentityRepoMockRecorder) FindByProviderUID(ctx, provider, providerUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProviderUID", reflect.TypeOf((*MockUserIdentityRepo)(nil).FindByProviderUID), ctx, provider, providerUID)
}

// FindByUserAndProvider mocks base method.
func (m *MockUserIdentityRepo) FindByUserAndProvider(ctx context.Context, userID int64, provider string) (*user_identity_entity.UserIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserAndProvider", ctx, userID, provider)
	ret0, _ := ret[0].(*user_identity_entity.UserIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserAndProvider indicates an expected call of FindByUserAndProvider.
func (mr *MockUserIdentityRepoMockRecorder) FindByUserAndProvider(ctx, userID, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserAndProvider", reflect.TypeOf((*MockUserIdentityRepo)(nil).FindByUserAndProvider), ctx, userID, provider)
}

// ListByUser mocks base method.
func (m *MockUserIdentityRepo) ListByUser(ctx context.Context, userID int64) ([]*user_identity_entity.UserIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]*user_identity_entity.UserIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockUserIdentityRepoMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockUserIdentityRepo)(nil).ListByUser), ctx, userID)
}
